# Generated by Django 3.2.9 on 2021-11-29 16:22

from django.db import migrations, models
import localflavor.br.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF de origem')),
                ('target', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF de destino')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Valor')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('creation', models.DateField(auto_now_add=True)),
                ('balance', models.PositiveIntegerField(default=1000)),
                ('number', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
